# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(360, 470)
        self.TabMenuIntervals = QtWidgets.QTabWidget(MainForm)
        self.TabMenuIntervals.setEnabled(True)
        self.TabMenuIntervals.setGeometry(QtCore.QRect(10, 70, 331, 201))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.TabMenuIntervals.setFont(font)
        self.TabMenuIntervals.setObjectName("TabMenuIntervals")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.checkBox_WorkOff = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_WorkOff.setGeometry(QtCore.QRect(220, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.checkBox_WorkOff.setFont(font)
        self.checkBox_WorkOff.setObjectName("checkBox_WorkOff")
        self.spinBox_WorkSecunde = QtWidgets.QSpinBox(self.tab_7)
        self.spinBox_WorkSecunde.setGeometry(QtCore.QRect(240, 80, 61, 31))
        self.spinBox_WorkSecunde.setMaximum(60)
        self.spinBox_WorkSecunde.setObjectName("spinBox_WorkSecunde")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(140, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_WorkMinute = QtWidgets.QSpinBox(self.tab_7)
        self.spinBox_WorkMinute.setGeometry(QtCore.QRect(140, 80, 61, 31))
        self.spinBox_WorkMinute.setMinimum(0)
        self.spinBox_WorkMinute.setMaximum(999)
        self.spinBox_WorkMinute.setProperty("value", 25)
        self.spinBox_WorkMinute.setObjectName("spinBox_WorkMinute")
        self.spinBox_WorkInterval = QtWidgets.QSpinBox(self.tab_7)
        self.spinBox_WorkInterval.setGeometry(QtCore.QRect(10, 80, 51, 31))
        self.spinBox_WorkInterval.setMinimum(0)
        self.spinBox_WorkInterval.setProperty("value", 4)
        self.spinBox_WorkInterval.setObjectName("spinBox_WorkInterval")
        self.horizontalSlider_workMinute = QtWidgets.QSlider(self.tab_7)
        self.horizontalSlider_workMinute.setGeometry(QtCore.QRect(10, 130, 191, 16))
        self.horizontalSlider_workMinute.setMaximum(240)
        self.horizontalSlider_workMinute.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_workMinute.setObjectName("horizontalSlider_workMinute")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelTitleWorkTime = QtWidgets.QLabel(self.tab_7)
        self.labelTitleWorkTime.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.labelTitleWorkTime.setFont(font)
        self.labelTitleWorkTime.setObjectName("labelTitleWorkTime")
        self.label_5 = QtWidgets.QLabel(self.tab_7)
        self.label_5.setGeometry(QtCore.QRect(240, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_WorkOff.raise_()
        self.spinBox_WorkSecunde.raise_()
        self.label_4.raise_()
        self.spinBox_WorkMinute.raise_()
        self.spinBox_WorkInterval.raise_()
        self.horizontalSlider_workMinute.raise_()
        self.label_3.raise_()
        self.labelTitleWorkTime.raise_()
        self.label_5.raise_()
        self.TabMenuIntervals.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.spinBox_BreakSecunde = QtWidgets.QSpinBox(self.tab_8)
        self.spinBox_BreakSecunde.setGeometry(QtCore.QRect(110, 80, 61, 31))
        self.spinBox_BreakSecunde.setMaximum(60)
        self.spinBox_BreakSecunde.setObjectName("spinBox_BreakSecunde")
        self.checkBox_BreakOff = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_BreakOff.setGeometry(QtCore.QRect(220, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.checkBox_BreakOff.setFont(font)
        self.checkBox_BreakOff.setObjectName("checkBox_BreakOff")
        self.label_6 = QtWidgets.QLabel(self.tab_8)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinBox_BreakMinute = QtWidgets.QSpinBox(self.tab_8)
        self.spinBox_BreakMinute.setGeometry(QtCore.QRect(10, 80, 61, 31))
        self.spinBox_BreakMinute.setMaximum(999)
        self.spinBox_BreakMinute.setProperty("value", 5)
        self.spinBox_BreakMinute.setObjectName("spinBox_BreakMinute")
        self.horizontalSlider_BreakMinute = QtWidgets.QSlider(self.tab_8)
        self.horizontalSlider_BreakMinute.setGeometry(QtCore.QRect(10, 130, 191, 16))
        self.horizontalSlider_BreakMinute.setMaximum(240)
        self.horizontalSlider_BreakMinute.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BreakMinute.setObjectName("horizontalSlider_BreakMinute")
        self.label_8 = QtWidgets.QLabel(self.tab_8)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_8)
        self.label_9.setGeometry(QtCore.QRect(110, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.TabMenuIntervals.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.spinBox_BigBreakSecunde = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_BigBreakSecunde.setGeometry(QtCore.QRect(110, 80, 61, 31))
        self.spinBox_BigBreakSecunde.setMaximum(60)
        self.spinBox_BigBreakSecunde.setObjectName("spinBox_BigBreakSecunde")
        self.checkBox_BigBreakOff = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_BigBreakOff.setGeometry(QtCore.QRect(220, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.checkBox_BigBreakOff.setFont(font)
        self.checkBox_BigBreakOff.setObjectName("checkBox_BigBreakOff")
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spinBox_BigBreakMinute = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_BigBreakMinute.setGeometry(QtCore.QRect(10, 80, 61, 31))
        self.spinBox_BigBreakMinute.setMaximum(999)
        self.spinBox_BigBreakMinute.setProperty("value", 15)
        self.spinBox_BigBreakMinute.setObjectName("spinBox_BigBreakMinute")
        self.horizontalSlider_BigBreak = QtWidgets.QSlider(self.tab_9)
        self.horizontalSlider_BigBreak.setGeometry(QtCore.QRect(10, 130, 191, 16))
        self.horizontalSlider_BigBreak.setMaximum(240)
        self.horizontalSlider_BigBreak.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BigBreak.setObjectName("horizontalSlider_BigBreak")
        self.label_12 = QtWidgets.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_9)
        self.label_13.setGeometry(QtCore.QRect(110, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.TabMenuIntervals.addTab(self.tab_9, "")
        self.label_header = QtWidgets.QLabel(MainForm)
        self.label_header.setGeometry(QtCore.QRect(0, 0, 351, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.pushButton_StartAndStop = QtWidgets.QPushButton(MainForm)
        self.pushButton_StartAndStop.setGeometry(QtCore.QRect(10, 300, 101, 51))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        self.pushButton_StartAndStop.setFont(font)
        self.pushButton_StartAndStop.setObjectName("pushButton_StartAndStop")
        self.pushButton_Settings = QtWidgets.QPushButton(MainForm)
        self.pushButton_Settings.setGeometry(QtCore.QRect(280, 300, 61, 51))
        self.pushButton_Settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pic/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Settings.setIcon(icon)
        self.pushButton_Settings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.pushButton_Reset = QtWidgets.QPushButton(MainForm)
        self.pushButton_Reset.setGeometry(QtCore.QRect(140, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.listView = QtWidgets.QListView(MainForm)
        self.listView.setGeometry(QtCore.QRect(0, 380, 361, 91))
        self.listView.setAutoScroll(True)
        self.listView.setObjectName("listView")
        self.lcdNumber_Minute = QtWidgets.QLCDNumber(MainForm)
        self.lcdNumber_Minute.setEnabled(True)
        self.lcdNumber_Minute.setGeometry(QtCore.QRect(60, 140, 91, 111))
        self.lcdNumber_Minute.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Minute.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_Minute.setLineWidth(1)
        self.lcdNumber_Minute.setDigitCount(2)
        self.lcdNumber_Minute.setProperty("intValue", 25)
        self.lcdNumber_Minute.setObjectName("lcdNumber_Minute")
        self.label_TypeInterval = QtWidgets.QLabel(MainForm)
        self.label_TypeInterval.setEnabled(True)
        self.label_TypeInterval.setGeometry(QtCore.QRect(71, 90, 211, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        self.label_TypeInterval.setFont(font)
        self.label_TypeInterval.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_TypeInterval.setTextFormat(QtCore.Qt.AutoText)
        self.label_TypeInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TypeInterval.setObjectName("label_TypeInterval")
        self.lcdNumber_Second = QtWidgets.QLCDNumber(MainForm)
        self.lcdNumber_Second.setEnabled(True)
        self.lcdNumber_Second.setGeometry(QtCore.QRect(200, 140, 91, 111))
        self.lcdNumber_Second.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Second.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_Second.setSmallDecimalPoint(False)
        self.lcdNumber_Second.setDigitCount(2)
        self.lcdNumber_Second.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_Second.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_Second.setProperty("intValue", 59)
        self.lcdNumber_Second.setObjectName("lcdNumber_Second")
        self.label_dotsTime = QtWidgets.QLabel(MainForm)
        self.label_dotsTime.setEnabled(True)
        self.label_dotsTime.setGeometry(QtCore.QRect(160, 140, 31, 111))
        font = QtGui.QFont()
        font.setFamily("Free Helvetian Condensed")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_dotsTime.setFont(font)
        self.label_dotsTime.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_dotsTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dotsTime.setObjectName("label_dotsTime")

        self.retranslateUi(MainForm)
        self.TabMenuIntervals.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "tomato"))
        self.checkBox_WorkOff.setText(_translate("MainForm", "on"))
        self.label_4.setText(_translate("MainForm", "мин."))
        self.label_3.setText(_translate("MainForm", "интервалы"))
        self.labelTitleWorkTime.setText(_translate("MainForm", "Таймер рабочего времени"))
        self.label_5.setText(_translate("MainForm", "сек."))
        self.TabMenuIntervals.setTabText(self.TabMenuIntervals.indexOf(self.tab_7), _translate("MainForm", "Работа"))
        self.checkBox_BreakOff.setText(_translate("MainForm", "on"))
        self.label_6.setText(_translate("MainForm", "мин."))
        self.label_8.setText(_translate("MainForm", "Таймер маленького перерыва"))
        self.label_9.setText(_translate("MainForm", "сек."))
        self.TabMenuIntervals.setTabText(self.TabMenuIntervals.indexOf(self.tab_8), _translate("MainForm", "Перерыв"))
        self.checkBox_BigBreakOff.setText(_translate("MainForm", "on"))
        self.label_10.setText(_translate("MainForm", "мин."))
        self.label_12.setText(_translate("MainForm", "Таймер большого перерыва"))
        self.label_13.setText(_translate("MainForm", "сек."))
        self.TabMenuIntervals.setTabText(self.TabMenuIntervals.indexOf(self.tab_9), _translate("MainForm", "Отдых"))
        self.label_header.setText(_translate("MainForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#555753;\">Метод помидора</span></p></body></html>"))
        self.pushButton_StartAndStop.setText(_translate("MainForm", "старт"))
        self.pushButton_Reset.setText(_translate("MainForm", "сброс"))
        self.label_TypeInterval.setText(_translate("MainForm", "Тип"))
        self.label_dotsTime.setText(_translate("MainForm", ":"))

